// Code generated by hertz generator.

package feed

import (
	"context"
	"douyin/biz/config"
	"douyin/biz/model/api"
	"douyin/biz/model/feed"
	"douyin/biz/model/query"
	"douyin/biz/pack"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"gorm.io/driver/mysql"
	"gorm.io/gorm"
	"time"
)

// Feed .
// @router /douyin/feed/ [GET]
func Feed(ctx context.Context, c *app.RequestContext) {
	var err error
	var req feed.DouyinFeedRequest
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(feed.DouyinFeedResponse)

	LastTime := req.GetLatestTime()
	if LastTime == 0 {
		LastTime = time.Now().Unix()
		resp.NextTime = LastTime
	}

	Token := req.GetToken()
	claims, err := pack.ParseToken(Token)
	userId := int64(0)
	if err == nil {
		userId = claims.ID
	}
	//fmt.Println(Token)

	db, err := gorm.Open(mysql.Open(config.MySQLDSN), &gorm.Config{})
	query.SetDefault(db)

	result, err := query.Q.Video.Where(query.Video.ReleaseTime.Lte(LastTime)).Order(query.Video.ReleaseTime.Desc()).Limit(config.MaxVideoListSize).Find()

	if err != nil {
		resp.StatusMsg = err.Error()
		resp.StatusCode = consts.StatusInternalServerError
		return
	}

	for _, v := range result {
		user, _ := query.Q.User.Where(query.User.ID.Eq(v.UserID)).Take()
		LastTime = Min(LastTime, v.ReleaseTime)
		_, err := query.Q.Favorite.Where(query.Favorite.VideoID.Eq(v.ID), query.Favorite.UserID.Eq(userId)).Take()
		resp.VideoList = append(resp.VideoList, api.Video{
			Id: v.ID,
			Author: &api.User{
				Id:            user.ID,
				Name:          user.Username,
				FollowCount:   user.FollowCount,
				FollowerCount: user.FollowerCount,
				IsFollow:      user.IsFollow == 1,
			},
			PlayUrl:       config.ServerRootUrl + v.PlayURL,
			CoverUrl:      "https://cdn.pixabay.com/photo/2016/03/27/18/10/bear-1283347_1280.jpg",
			FavoriteCount: v.FavoriteCount,
			CommentCount:  v.CommentCount,
			IsFavorite:    err == nil,
			Title:         v.Title,
		})
	}

	resp.StatusCode = config.StatusOK
	resp.StatusMsg = consts.StatusMessage(consts.StatusOK)
	c.JSON(consts.StatusOK, resp)
}

func Min(time int64, time2 int64) int64 {
	if time < time2 {
		return time
	}
	return time2
}
