// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameComment = "comment"

// Comment mapped from table <comment>
type Comment struct {
	UserID     int64  `gorm:"column:user_id;not null" json:"user_id"`         // 用户id
	ID         int64  `gorm:"column:id;primaryKey" json:"id"`                 // 评论id
	Text       string `gorm:"column:text;not null" json:"text"`               // 评论内容
	CreateDate int64  `gorm:"column:create_date;not null" json:"create_date"` // 提交时间
}

// TableName Comment's table name
func (*Comment) TableName() string {
	return TableNameComment
}
