// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameCommentList = "comment_list"

// CommentList mapped from table <comment_list>
type CommentList struct {
	ID      int64 `gorm:"column:id;not null" json:"id"`             // 评论id
	VideoID int64 `gorm:"column:video_id;not null" json:"video_id"` // 视频id
}

// TableName CommentList's table name
func (*CommentList) TableName() string {
	return TableNameCommentList
}
