// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameFollowList = "follow_list"

// FollowList mapped from table <follow_list>
type FollowList struct {
	FollowerID int64 `gorm:"column:follower_id;not null" json:"follower_id"` // 关注人ID
	UserID     int64 `gorm:"column:user_id;not null" json:"user_id"`         // 用户ID
}

// TableName FollowList's table name
func (*FollowList) TableName() string {
	return TableNameFollowList
}
