// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package orm_gen

const TableNameMessage = "message"

// Message mapped from table <message>
type Message struct {
	ID         int64  `gorm:"column:id;primaryKey" json:"id"`
	ToUserID   int64  `gorm:"column:to_user_id;not null" json:"to_user_id"`
	FromUserID int64  `gorm:"column:from_user_id;not null" json:"from_user_id"`
	Content    string `gorm:"column:content;not null" json:"content"`
	CreateTime string `gorm:"column:create_time;not null" json:"create_time"`
}

// TableName Message's table name
func (*Message) TableName() string {
	return TableNameMessage
}
