// Code generated by hertz generator.

package favorite

import (
	"context"

	favorite "douyin/biz/model/favorite"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
)

// FavoriteList .
// @router /douyin/user/ [GET]
func FavoriteList(ctx context.Context, c *app.RequestContext) {
	var err error
	var req favorite._favorite_list_request
	err = c.BindAndValidate(&req)
	if err != nil {
		c.String(consts.StatusBadRequest, err.Error())
		return
	}

	resp := new(favorite._favorite_list_response)

	c.JSON(consts.StatusOK, resp)
}
