// Code generated by hertz generator. DO NOT EDIT.

package router

import (
	comment "douyin/biz/router/comment"
	favorite "douyin/biz/router/favorite"
	feed "douyin/biz/router/feed"
	publish "douyin/biz/router/publish"
	relation "douyin/biz/router/relation"
	user "douyin/biz/router/user"
	"github.com/cloudwego/hertz/pkg/app/server"
)

// GeneratedRegister registers routers generated by IDL.
func GeneratedRegister(r *server.Hertz) {
	//INSERT_POINT: DO NOT DELETE THIS LINE!
	relation.Register(r)

	comment.Register(r)

	favorite.Register(r)

	user.Register(r)

	feed.Register(r)

	publish.Register(r)
}
